plugins:
  discourse_brandme_community_access_enabled:
    default: false
  discourse_brandme_community_access_secret:
    default: ""
    type: list
  discourse_brandme_community_access_product_group_mappings:
    default: ""
    type: list
